Repository Klebert-Engineering/stx, pull requests merged in 2021-03, with the labels that each got.

#2 Add function for joining a string range
  include/stx/string.h
  test/src/string.cpp
Labels: enhancement

#1 Add function for converting range to hex
  CMakeLists.txt
  include/stx/string.h
  test/CMakeLists.txt
  test/src/string.cpp
Labels: enhancement

#3 Use ull as base for accumulate in stx::string::join
  include/stx/string.h
Labels: bug

#4 Enable -Wall & -Werror for unit-tests
  include/stx/string.h
  test/CMakeLists.txt
Labels: enhancement :star:

#6 Fix type deduction bug of to_hex
  include/stx/string.h
  test/src/string.cpp
Labels: bug :bomb:

#7 Added missing iterator include
  include/stx/string.h
Labels: bug :bomb:

#8 String: to_string support string_view
  include/stx/string.h
Labels: enhancement :star:

#9 String: split use string_view
  include/stx/string.h
  test/src/string.cpp
Labels: enhancement :star:

#10 Implement stx::format
  include/stx/format.h
  include/stx/format_impl.h
  include/stx/formatter.h
  test/CMakeLists.txt
  test/src/format.cpp
Labels: enhancement :star:, feature :gift:

#11 Add tests for `get_as_string`
  include/stx/string.h
  test/src/string.cpp
Labels: bug :bomb:, enhancement :star:

#12 Add float format test
  include/stx/formatter.h
  test/src/format.cpp
Labels: bug :bomb:
